name: Close All Issues and PRs

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "CONFIRM" to proceed with closing all issues and PRs'
        required: true
        default: ''
      close_message:
        description: 'Message to include when closing issues and PRs'
        required: false
        default: 'Closing as part of repository cleanup.'

jobs:
  close-all:
    if: ${{ github.event.inputs.confirm == 'CONFIRM' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
      
      - name: Configure GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      
      - name: Close all open issues
        run: |
          CLOSE_MESSAGE="${{ github.event.inputs.close_message }}"
          echo "Closing all open issues..."
          
          # Get all open issues (process in batches to handle pagination)
          # We'll use the created date to process in batches
          MAX_BATCH_SIZE=100
          
          echo "Fetching and closing all open issues..."
          while true; do
            # Get a batch of open issues
            ISSUES=$(gh issue list --state open --limit $MAX_BATCH_SIZE --json number,title --jq '.[] | [.number, .title] | @tsv')
            
            # If no issues left, we're done
            if [ -z "$ISSUES" ]; then
              echo "No more open issues found."
              break
            fi
            
            # Process this batch
            echo "$ISSUES" | while IFS=
\t' read -r NUMBER TITLE; do
              echo "Closing issue #$NUMBER: $TITLE"
              gh issue close $NUMBER --comment "$CLOSE_MESSAGE"
              # Small delay to avoid rate limiting
              sleep 1
            done
          done
      
      - name: Close all open pull requests
        run: |
          CLOSE_MESSAGE="${{ github.event.inputs.close_message }}"
          echo "Closing all open pull requests..."
          
          # Get all open PRs (process in batches to handle pagination)
          MAX_BATCH_SIZE=100
          
          echo "Fetching and closing all open pull requests..."
          while true; do
            # Get a batch of open PRs
            PRS=$(gh pr list --state open --limit $MAX_BATCH_SIZE --json number,title --jq '.[] | [.number, .title] | @tsv')
            
            # If no PRs left, we're done
            if [ -z "$PRS" ]; then
              echo "No more open pull requests found."
              break
            fi
            
            # Process this batch
            echo "$PRS" | while IFS=
\t' read -r NUMBER TITLE; do
              echo "Closing PR #$NUMBER: $TITLE"
              gh pr close $NUMBER --comment "$CLOSE_MESSAGE"
              # Small delay to avoid rate limiting
              sleep 1
            done
          done
