name: Close All Issues and PRs

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "CONFIRM" to proceed with closing all issues and PRs'
        required: true
        default: ''
      close_message:
        description: 'Message to include when closing issues and PRs'
        required: false
        default: 'Closing as part of repository cleanup.'

jobs:
  close-all:
    if: ${{ github.event.inputs.confirm == 'CONFIRM' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || sudo apt install curl -y
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
      
      - name: Close all open issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOSE_MESSAGE: ${{ github.event.inputs.close_message }}
        run: |
          echo "Closing all open issues..."
          
          while : ; do
            # Get a batch of open issues (max 100 at a time)
            ISSUES=$(gh issue list --state open --limit 100 --json number,title --jq '.[] | [.number, .title] | @tsv')
            
            # If no issues left, exit the loop
            if [ -z "$ISSUES" ]; then
              echo "No more open issues to close."
              break
            fi
            
            # Process all issues in this batch
            echo "$ISSUES" | while IFS=$'\t' read -r NUMBER TITLE; do
              echo "Closing issue #$NUMBER: $TITLE"
              gh issue close "$NUMBER" --comment "$CLOSE_MESSAGE"
              sleep 0.5  # Small delay to avoid rate limiting
            done
          done
      
      - name: Close all open pull requests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOSE_MESSAGE: ${{ github.event.inputs.close_message }}
        run: |
          echo "Closing all open pull requests..."
          
          while : ; do
            # Get a batch of open PRs (max 100 at a time)
            PRS=$(gh pr list --state open --limit 100 --json number,title --jq '.[] | [.number, .title] | @tsv')
            
            # If no PRs left, exit the loop
            if [ -z "$PRS" ]; then
              echo "No more open pull requests to close."
              break
            fi
            
            # Process all PRs in this batch
            echo "$PRS" | while IFS=$'\t' read -r NUMBER TITLE; do
              echo "Closing PR #$NUMBER: $TITLE"
              gh pr close "$NUMBER" --comment "$CLOSE_MESSAGE"
              sleep 0.5  # Small delay to avoid rate limiting
            done
          done
